/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectortbdii;

import java.awt.Toolkit;
import javax.swing.ButtonGroup;
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import redis.clients.jedis.exceptions.JedisException;

/**
 *
 * @author acer
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        //this.setUndecorated(true);
        this.setResizable(false);
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int ancho = (int) tk.getScreenSize().getWidth() / 2;
        int alto = (int) tk.getScreenSize().getHeight() / 2;
        this.setSize(ancho, alto);
        this.setLocationRelativeTo(null);
        jd_login.setUndecorated(true);
        jd_login.setModal(true);//Bloquear otras ventanas
        jd_login.pack();//Acoplar el tamaño a la ventana a los elementos que incluye
        jd_login.setLocationRelativeTo(this);//Ubicar la ventana en una posicion
        jd_login.setResizable(false);//No se puede modificar el tamaño
        jd_login.setVisible(true);
        //Height = (int) jp_principal.getSize().getHeight();
        //Width = (int) jp_principal.getSize().getWidth();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_login = new javax.swing.JDialog();
        lb_foto = new javax.swing.JLabel();
        tf_login_password = new javax.swing.JPasswordField();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        tf_login_username = new javax.swing.JTextField();
        jd_agregar_profesor = new javax.swing.JDialog();
        tf_prof_nombre = new javax.swing.JTextField();
        tf_prof_apellido = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        rb_prof_male = new javax.swing.JRadioButton();
        rb_prof_female = new javax.swing.JRadioButton();
        jdc_prof_nacimiento = new com.toedter.calendar.JDateChooser();
        tf_prof_telefono = new javax.swing.JTextField();
        sp_prof_sueldo = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        sp_prof_xp = new javax.swing.JSpinner();
        jd_editar_profesor = new javax.swing.JDialog();
        tf_editar_profesor_nombre = new javax.swing.JTextField();
        tf_editar_profesor_apellido = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jButton28 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        rb_editar_profesor_male = new javax.swing.JRadioButton();
        rb_editar_profesor_female = new javax.swing.JRadioButton();
        jdc_editar_profesor_fecha = new com.toedter.calendar.JDateChooser();
        tf_editar_profesor_telefono = new javax.swing.JTextField();
        sp_editar_profesor_sueldo = new javax.swing.JSpinner();
        jLabel48 = new javax.swing.JLabel();
        sp_editar_profesor_xp = new javax.swing.JSpinner();
        jd_agregar_alumno = new javax.swing.JDialog();
        tf_nombre2 = new javax.swing.JTextField();
        tf_correo4 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton25 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        tf_correo5 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jd_editar_alumno = new javax.swing.JDialog();
        tf_nombre3 = new javax.swing.JTextField();
        tf_correo6 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jButton26 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        tf_correo7 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jd_modulo = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_modulo = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        cb_modulo = new javax.swing.JComboBox<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        JD_agregarVehiculo = new javax.swing.JDialog();
        L_vehiculo = new javax.swing.JLabel();
        L_uso = new javax.swing.JLabel();
        TF_uso = new javax.swing.JTextField();
        L_tamano = new javax.swing.JLabel();
        TF_tamano = new javax.swing.JTextField();
        L_tarifa = new javax.swing.JLabel();
        TF_tarifa = new javax.swing.JTextField();
        L_consumo = new javax.swing.JLabel();
        TF_consumo = new javax.swing.JTextField();
        L_kmRecorridos = new javax.swing.JLabel();
        TF_kmRecorridos = new javax.swing.JTextField();
        L_tipoVehiculo = new javax.swing.JLabel();
        CB_tipoVehiculo = new javax.swing.JComboBox<>();
        B_agregarVehiculo = new javax.swing.JButton();
        JD_agregarClase = new javax.swing.JDialog();
        L_clase = new javax.swing.JLabel();
        L_idProfesor = new javax.swing.JLabel();
        TF_idProfesor = new javax.swing.JTextField();
        L_idAlumno = new javax.swing.JLabel();
        TF_idAlumno = new javax.swing.JTextField();
        L_agregarClase_tipoClase = new javax.swing.JLabel();
        CB_agregarClase_tipoClase = new javax.swing.JComboBox<>();
        L_examenPractico = new javax.swing.JLabel();
        TF_examenPractico = new javax.swing.JTextField();
        L_examenTeorico = new javax.swing.JLabel();
        TF_examenTeorico = new javax.swing.JTextField();
        B_agregarClase = new javax.swing.JButton();
        JD_agregarPago = new javax.swing.JDialog();
        L_pago = new javax.swing.JLabel();
        L_agregarPago_idAlumno = new javax.swing.JLabel();
        TF_agregarPago_idAlumno = new javax.swing.JTextField();
        L_costoMatricula = new javax.swing.JLabel();
        TF_costoMatricula = new javax.swing.JTextField();
        L_costoEnsenanzaTeorica = new javax.swing.JLabel();
        TF_costoEnsenanzaTeorica = new javax.swing.JTextField();
        L_costoTramitacionDocs = new javax.swing.JLabel();
        TF_costoTramitacionDocs = new javax.swing.JTextField();
        L_costoEnsenanzaPractica = new javax.swing.JLabel();
        TF_costoEnsenanzaPractica = new javax.swing.JTextField();
        B_agregarPago = new javax.swing.JButton();
        jp_principal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        MI_agregarVehiculo = new javax.swing.JMenuItem();
        MI_agregarClase = new javax.swing.JMenuItem();
        MI_agregarPago = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jd_login.setTitle("Login");

        lb_foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton6.setText("Acceder");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        jButton20.setText("Crear cuenta");

        jLabel19.setText("¿No tienes cuenta?");

        jButton22.setText("Cerrar");
        jButton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton22MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_loginLayout = new javax.swing.GroupLayout(jd_login.getContentPane());
        jd_login.getContentPane().setLayout(jd_loginLayout);
        jd_loginLayout.setHorizontalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_loginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton20))
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_login_password, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addGroup(jd_loginLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_login_username))
                        .addGap(0, 153, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(lb_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_loginLayout.setVerticalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(lb_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_login_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_login_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(33, 33, 33)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton20)
                    .addComponent(jLabel19)
                    .addComponent(jButton22))
                .addContainerGap())
        );

        jd_agregar_profesor.setTitle("Agregar Profesor");

        jLabel13.setText("Nombre");

        jLabel14.setText("Apellido");

        jLabel15.setText("Fecha de Nacimiento");

        jLabel16.setText("Telefono");

        jLabel17.setText("Sueldo");

        jButton19.setText("Agregar");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jLabel20.setText("Genero");

        buttonGroup1.add(rb_prof_male);
        rb_prof_male.setText("Masculino");

        buttonGroup1.add(rb_prof_female);
        rb_prof_female.setText("Femenino");

        jLabel18.setText("Años de Experiencia");

        javax.swing.GroupLayout jd_agregar_profesorLayout = new javax.swing.GroupLayout(jd_agregar_profesor.getContentPane());
        jd_agregar_profesor.getContentPane().setLayout(jd_agregar_profesorLayout);
        jd_agregar_profesorLayout.setHorizontalGroup(
            jd_agregar_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregar_profesorLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregar_profesorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jd_agregar_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jd_agregar_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregar_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tf_prof_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                        .addComponent(tf_prof_apellido)
                        .addGroup(jd_agregar_profesorLayout.createSequentialGroup()
                            .addComponent(rb_prof_male)
                            .addGap(18, 18, 18)
                            .addComponent(rb_prof_female))
                        .addComponent(jdc_prof_nacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_prof_telefono))
                    .addComponent(sp_prof_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_prof_xp, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
        jd_agregar_profesorLayout.setVerticalGroup(
            jd_agregar_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregar_profesorLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jd_agregar_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_prof_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jd_agregar_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(tf_prof_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_agregar_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(rb_prof_male)
                    .addComponent(rb_prof_female))
                .addGap(22, 22, 22)
                .addGroup(jd_agregar_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdc_prof_nacimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jd_agregar_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_prof_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_agregar_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(sp_prof_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_agregar_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp_prof_xp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jd_editar_profesor.setTitle("Editar Profesor");

        jLabel42.setText("Nombre");

        jLabel43.setText("Apellido");

        jLabel44.setText("Fecha de Nacimiento");

        jLabel45.setText("Telefono");

        jLabel46.setText("Sueldo");

        jButton28.setText("Guardar cambios");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });

        jLabel47.setText("Genero");

        buttonGroup1.add(rb_editar_profesor_male);
        rb_editar_profesor_male.setText("Masculino");

        buttonGroup1.add(rb_editar_profesor_female);
        rb_editar_profesor_female.setText("Femenino");

        jLabel48.setText("Años de Experiencia");

        javax.swing.GroupLayout jd_editar_profesorLayout = new javax.swing.GroupLayout(jd_editar_profesor.getContentPane());
        jd_editar_profesor.getContentPane().setLayout(jd_editar_profesorLayout);
        jd_editar_profesorLayout.setHorizontalGroup(
            jd_editar_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_editar_profesorLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_editar_profesorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jd_editar_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel48)
                    .addComponent(jLabel43)
                    .addComponent(jLabel44)
                    .addComponent(jLabel45)
                    .addComponent(jLabel46)
                    .addComponent(jLabel47)
                    .addComponent(jLabel42))
                .addGap(18, 18, 18)
                .addGroup(jd_editar_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_editar_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tf_editar_profesor_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                        .addComponent(tf_editar_profesor_apellido)
                        .addGroup(jd_editar_profesorLayout.createSequentialGroup()
                            .addComponent(rb_editar_profesor_male)
                            .addGap(18, 18, 18)
                            .addComponent(rb_editar_profesor_female))
                        .addComponent(jdc_editar_profesor_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_editar_profesor_telefono))
                    .addComponent(sp_editar_profesor_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_editar_profesor_xp, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
        jd_editar_profesorLayout.setVerticalGroup(
            jd_editar_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_editar_profesorLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jd_editar_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_editar_profesor_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addGap(18, 18, 18)
                .addGroup(jd_editar_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel43)
                    .addComponent(tf_editar_profesor_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_editar_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(rb_editar_profesor_male)
                    .addComponent(rb_editar_profesor_female))
                .addGap(22, 22, 22)
                .addGroup(jd_editar_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdc_editar_profesor_fecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jd_editar_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(tf_editar_profesor_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_editar_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel46)
                    .addComponent(sp_editar_profesor_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_editar_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp_editar_profesor_xp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jd_agregar_alumno.setTitle("Agregar Alumno");

        jLabel23.setText("Nombre");

        jLabel24.setText("Apellido");

        jLabel25.setText("Fecha de Nacimiento");

        jLabel26.setText("Telefono");

        jLabel27.setText("Tipo Licencia");

        jButton25.setText("Agregar");

        jLabel28.setText("Genero");

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("Masculino");

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("Femenino");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Liviana", "Pesada" }));

        javax.swing.GroupLayout jd_agregar_alumnoLayout = new javax.swing.GroupLayout(jd_agregar_alumno.getContentPane());
        jd_agregar_alumno.getContentPane().setLayout(jd_agregar_alumnoLayout);
        jd_agregar_alumnoLayout.setHorizontalGroup(
            jd_agregar_alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregar_alumnoLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregar_alumnoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jd_agregar_alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jd_agregar_alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_nombre2, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(tf_correo4)
                    .addGroup(jd_agregar_alumnoLayout.createSequentialGroup()
                        .addComponent(jRadioButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton6))
                    .addComponent(jDateChooser3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_correo5)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60))
        );
        jd_agregar_alumnoLayout.setVerticalGroup(
            jd_agregar_alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregar_alumnoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jd_agregar_alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jd_agregar_alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(tf_correo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_agregar_alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addGap(22, 22, 22)
                .addGroup(jd_agregar_alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jd_agregar_alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tf_correo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jd_agregar_alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jd_editar_alumno.setTitle("Editar Alumno");

        jLabel29.setText("Nombre");

        jLabel30.setText("Apellido");

        jLabel31.setText("Fecha de Nacimiento");

        jLabel32.setText("Telefono");

        jLabel33.setText("Tipo Licencia");

        jButton26.setText("Guardar cambios");

        jLabel34.setText("Genero");

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("Masculino");

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setText("Femenino");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Liviana", "Pesada" }));

        javax.swing.GroupLayout jd_editar_alumnoLayout = new javax.swing.GroupLayout(jd_editar_alumno.getContentPane());
        jd_editar_alumno.getContentPane().setLayout(jd_editar_alumnoLayout);
        jd_editar_alumnoLayout.setHorizontalGroup(
            jd_editar_alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_editar_alumnoLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_editar_alumnoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jd_editar_alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34)
                    .addComponent(jLabel29))
                .addGap(18, 18, 18)
                .addGroup(jd_editar_alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_nombre3, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(tf_correo6)
                    .addGroup(jd_editar_alumnoLayout.createSequentialGroup()
                        .addComponent(jRadioButton7)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton8))
                    .addComponent(jDateChooser4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_correo7)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60))
        );
        jd_editar_alumnoLayout.setVerticalGroup(
            jd_editar_alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_editar_alumnoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jd_editar_alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGap(18, 18, 18)
                .addGroup(jd_editar_alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(tf_correo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_editar_alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton8))
                .addGap(22, 22, 22)
                .addGroup(jd_editar_alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jd_editar_alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(tf_correo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jd_editar_alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jd_modulo.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jd_modulo.setTitle("Modulo");

        jt_modulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jt_modulo);

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Modificar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Obtener lista");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        cb_modulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Profesores", "Alumnos" }));
        cb_modulo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_moduloItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jd_moduloLayout = new javax.swing.GroupLayout(jd_modulo.getContentPane());
        jd_modulo.getContentPane().setLayout(jd_moduloLayout);
        jd_moduloLayout.setHorizontalGroup(
            jd_moduloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_moduloLayout.createSequentialGroup()
                .addGroup(jd_moduloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_moduloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE))
                    .addGroup(jd_moduloLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(103, 103, 103)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(cb_modulo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jd_moduloLayout.setVerticalGroup(
            jd_moduloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_moduloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jd_moduloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(cb_modulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        L_vehiculo.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        L_vehiculo.setText("Vehículo");

        L_uso.setText("Uso");

        L_tamano.setText("Tamaño");

        L_tarifa.setText("Tarifa");

        L_consumo.setText("Consumo");

        L_kmRecorridos.setText("Kilómetros Recorridos");

        L_tipoVehiculo.setText("Tipo de Vehículo");

        CB_tipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Liviano", "Pesado" }));

        B_agregarVehiculo.setText("Agregar");
        B_agregarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_agregarVehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JD_agregarVehiculoLayout = new javax.swing.GroupLayout(JD_agregarVehiculo.getContentPane());
        JD_agregarVehiculo.getContentPane().setLayout(JD_agregarVehiculoLayout);
        JD_agregarVehiculoLayout.setHorizontalGroup(
            JD_agregarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_agregarVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JD_agregarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_vehiculo)
                    .addGroup(JD_agregarVehiculoLayout.createSequentialGroup()
                        .addGroup(JD_agregarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_uso)
                            .addComponent(L_tamano)
                            .addComponent(L_tarifa)
                            .addComponent(L_consumo)
                            .addComponent(L_kmRecorridos)
                            .addComponent(L_tipoVehiculo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JD_agregarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TF_consumo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_tarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_tamano, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_uso, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JD_agregarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(CB_tipoVehiculo, javax.swing.GroupLayout.Alignment.LEADING, 0, 150, Short.MAX_VALUE)
                                .addComponent(TF_kmRecorridos, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addComponent(B_agregarVehiculo))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        JD_agregarVehiculoLayout.setVerticalGroup(
            JD_agregarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_agregarVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_vehiculo)
                .addGap(23, 23, 23)
                .addGroup(JD_agregarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_uso)
                    .addComponent(TF_uso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JD_agregarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_tamano)
                    .addComponent(TF_tamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JD_agregarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_tarifa)
                    .addComponent(TF_tarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JD_agregarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_consumo)
                    .addComponent(TF_consumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JD_agregarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_kmRecorridos)
                    .addComponent(TF_kmRecorridos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JD_agregarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_tipoVehiculo)
                    .addComponent(CB_tipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(B_agregarVehiculo)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        L_clase.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        L_clase.setText("Clase");

        L_idProfesor.setText("ID Profesor");

        L_idAlumno.setText("ID Alumno");

        L_agregarClase_tipoClase.setText("Tipo de Clase");

        CB_agregarClase_tipoClase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Práctica", "Teórica" }));

        L_examenPractico.setText("Examen Práctico");

        L_examenTeorico.setText("Examen Teórico");

        B_agregarClase.setText("Agregar");
        B_agregarClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_agregarClaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JD_agregarClaseLayout = new javax.swing.GroupLayout(JD_agregarClase.getContentPane());
        JD_agregarClase.getContentPane().setLayout(JD_agregarClaseLayout);
        JD_agregarClaseLayout.setHorizontalGroup(
            JD_agregarClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_agregarClaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JD_agregarClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_clase)
                    .addGroup(JD_agregarClaseLayout.createSequentialGroup()
                        .addGroup(JD_agregarClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_examenTeorico)
                            .addComponent(L_examenPractico)
                            .addComponent(L_agregarClase_tipoClase)
                            .addComponent(L_idAlumno)
                            .addComponent(L_idProfesor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JD_agregarClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TF_idProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_idAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CB_agregarClase_tipoClase, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JD_agregarClaseLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(JD_agregarClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TF_examenPractico, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TF_examenTeorico, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(B_agregarClase))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        JD_agregarClaseLayout.setVerticalGroup(
            JD_agregarClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_agregarClaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_clase)
                .addGap(18, 18, 18)
                .addGroup(JD_agregarClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_idProfesor)
                    .addComponent(TF_idProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JD_agregarClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_idAlumno)
                    .addComponent(TF_idAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JD_agregarClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_agregarClase_tipoClase)
                    .addComponent(CB_agregarClase_tipoClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JD_agregarClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_examenPractico)
                    .addComponent(TF_examenPractico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JD_agregarClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_examenTeorico)
                    .addComponent(TF_examenTeorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(B_agregarClase)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        L_pago.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        L_pago.setText("Pago");

        L_agregarPago_idAlumno.setText("ID Alumno");

        L_costoMatricula.setText("Costo de Matrícula");

        L_costoEnsenanzaTeorica.setText("Costo de Enseñanza Teórica");

        L_costoTramitacionDocs.setText("Costo de Tramitación de Documentos");

        L_costoEnsenanzaPractica.setText("Costo Enseñanza Práctica");

        B_agregarPago.setText("Agregar");
        B_agregarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_agregarPagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JD_agregarPagoLayout = new javax.swing.GroupLayout(JD_agregarPago.getContentPane());
        JD_agregarPago.getContentPane().setLayout(JD_agregarPagoLayout);
        JD_agregarPagoLayout.setHorizontalGroup(
            JD_agregarPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_agregarPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JD_agregarPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_pago)
                    .addGroup(JD_agregarPagoLayout.createSequentialGroup()
                        .addGroup(JD_agregarPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_agregarPago_idAlumno)
                            .addComponent(L_costoMatricula)
                            .addComponent(L_costoEnsenanzaTeorica)
                            .addComponent(L_costoTramitacionDocs)
                            .addComponent(L_costoEnsenanzaPractica))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JD_agregarPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TF_agregarPago_idAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_costoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_costoEnsenanzaTeorica, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_costoTramitacionDocs, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_costoEnsenanzaPractica, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(B_agregarPago))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        JD_agregarPagoLayout.setVerticalGroup(
            JD_agregarPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_agregarPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_pago)
                .addGap(18, 18, 18)
                .addGroup(JD_agregarPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_agregarPago_idAlumno)
                    .addComponent(TF_agregarPago_idAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JD_agregarPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_costoMatricula)
                    .addComponent(TF_costoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JD_agregarPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_costoEnsenanzaTeorica)
                    .addComponent(TF_costoEnsenanzaTeorica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JD_agregarPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_costoTramitacionDocs)
                    .addComponent(TF_costoTramitacionDocs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JD_agregarPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_costoEnsenanzaPractica)
                    .addComponent(TF_costoEnsenanzaPractica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(B_agregarPago)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Autoescuela");

        javax.swing.GroupLayout jp_principalLayout = new javax.swing.GroupLayout(jp_principal);
        jp_principal.setLayout(jp_principalLayout);
        jp_principalLayout.setHorizontalGroup(
            jp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jp_principalLayout.setVerticalGroup(
            jp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        jMenu1.setText("Menu");

        jMenuItem3.setText("Agregar Profesor");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem5.setText("Agregar Alumno");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        MI_agregarVehiculo.setText("Agregar Vehículo");
        MI_agregarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_agregarVehiculoActionPerformed(evt);
            }
        });
        jMenu1.add(MI_agregarVehiculo);

        MI_agregarClase.setText("Agregar Clase");
        MI_agregarClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_agregarClaseActionPerformed(evt);
            }
        });
        jMenu1.add(MI_agregarClase);

        MI_agregarPago.setText("Agregar Pago");
        MI_agregarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_agregarPagoActionPerformed(evt);
            }
        });
        jMenu1.add(MI_agregarPago);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Modulo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton22MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton22MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (tf_login_username.getText().equals("") && tf_login_password.getText().equals("")) {
            //JOptionPane.showMessageDialog(this, "Ha ingresado!");
            jd_login.dispose();
            this.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Username/Password incorrectos");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jt_modulo.getModel();
        model.setRowCount(0);
        jd_modulo.setModal(true);//Bloquear otras ventanas
        jd_modulo.pack();//Acoplar el tamaño a la ventana a los elementos que incluye
        jd_modulo.setLocationRelativeTo(this);//Ubicar la ventana en una posicion
        jd_modulo.setResizable(false);//No se puede modificar el tamaño
        jd_modulo.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        jd_agregar_profesor.setModal(true);//Bloquear otras ventanas
        jd_agregar_profesor.pack();//Acoplar el tamaño a la ventana a los elementos que incluye
        jd_agregar_profesor.setLocationRelativeTo(this);//Ubicar la ventana en una posicion
        jd_agregar_profesor.setResizable(false);//No se puede modificar el tamaño
        jd_agregar_profesor.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        jd_agregar_alumno.setModal(true);//Bloquear otras ventanas
        jd_agregar_alumno.pack();//Acoplar el tamaño a la ventana a los elementos que incluye
        jd_agregar_alumno.setLocationRelativeTo(this);//Ubicar la ventana en una posicion
        jd_agregar_alumno.setResizable(false);//No se puede modificar el tamaño
        jd_agregar_alumno.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        try {
            Redis r = new Redis();
            String uniqueID = UUID.randomUUID().toString();
            String genero = "";
            if (rb_prof_male.isSelected()) {
                genero = "Masculino";
            } else {
                genero = "Femenino";
            }
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(jdc_prof_nacimiento.getDate());
            Profesor pro = new Profesor(uniqueID, tf_prof_nombre.getText(), tf_prof_apellido.getText(),
                    genero, date, tf_prof_telefono.getText(),
                    sp_prof_sueldo.getValue().toString(), sp_prof_xp.getValue().toString());
            //Insertar en Redis
            r.createProfesor(pro);
            //Cerrar ventana
            jd_agregar_profesor.dispose();
            JOptionPane.showMessageDialog(this, "Se agregó el profesor exitosamente.\n"
                    + "Su ID es: " + uniqueID);
            //Limpiar campos
            tf_prof_nombre.setText(null);
            tf_prof_apellido.setText(null);
            jdc_prof_nacimiento.setDate(null);
            tf_prof_telefono.setText(null);
            sp_prof_sueldo.setValue(0);
            sp_prof_xp.setValue(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error al crear el profesor");
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.out.println(profes.size());
        if (cb_modulo.getSelectedItem().toString().equals("Profesores")) {
            profes.clear();
            Redis r = new Redis();
            ArrayList<String> keys = new ArrayList();
            keys = r.getAllKeys();
            try {
                for (int i = 0; i < keys.size(); i++) {
                    String tipo = r.getTipo(keys.get(i));
                    if (tipo.equals("Profesor")) {
                        Map<String, String> datos = new HashMap<String, String>();
                        datos = r.readObject(keys.get(i));
                        Profesor pro = new Profesor();
                        for (Map.Entry<String, String> entry : datos.entrySet()) {
                            //System.out.println("clave=" + entry.getKey() + ", valor=" + entry.getValue());
                            String id = "", nombre = "", apellido = "", genero = "", fecha_nacimiento = "", telefono = "", sueldo = "", experiencia = "";
                            if (entry.getKey().equals("id")) {
                                id = entry.getValue();
                                pro.setId(id);
                            } else if (entry.getKey().equals("nombre")) {
                                nombre = entry.getValue();
                                pro.setNombre(nombre);
                            } else if (entry.getKey().equals("apellido")) {
                                apellido = entry.getValue();
                                pro.setApellido(apellido);
                            } else if (entry.getKey().equals("genero")) {
                                genero = entry.getValue();
                                pro.setGenero(genero);
                            } else if (entry.getKey().equals("fecha_nacimiento")) {
                                fecha_nacimiento = entry.getValue();
                                pro.setFecha_nacimiento(fecha_nacimiento);
                            } else if (entry.getKey().equals("telefono")) {
                                telefono = entry.getValue();
                                pro.setTelefono(telefono);
                            } else if (entry.getKey().equals("sueldo")) {
                                sueldo = entry.getValue();
                                pro.setSueldo(sueldo);
                            } else if (entry.getKey().equals("experiencia")) {
                                experiencia = entry.getValue();
                                pro.setExperiencia(experiencia);
                            }
                        }
                        profes.add(pro);
                    } //else if (tipo.equals("Alumno")) {
//                        Map<String, String> datos = new HashMap<String, String>();
//                        datos = r.readObject(keys.get(i));
//                        for (Map.Entry<String, String> entry : datos.entrySet()) {
//                            String id = "", nombre = "", apellido = "", genero = "", fecha_nacimiento = "", telefono = "", tipo_licencia = "";
//                            if (entry.getKey().equals("id")) {
//                                id = entry.getValue();
//                            } else if (entry.getKey().equals("nombre")) {
//                                nombre = entry.getValue();
//                            } else if (entry.getKey().equals("apellido")) {
//                                apellido = entry.getValue();
//                            } else if (entry.getKey().equals("genero")) {
//                                genero = entry.getValue();
//                            } else if (entry.getKey().equals("fecha_nacimiento")) {
//                                fecha_nacimiento = entry.getValue();
//                            } else if (entry.getKey().equals("telefono")) {
//                                telefono = entry.getValue();
//                            } else if (entry.getKey().equals("tipo_licencia")) {
//                                tipo_licencia = entry.getValue();
//                            }
//                            Alumno alu = new Alumno(id, nombre, apellido, genero, fecha_nacimiento, telefono, tipo_licencia);
//                            alumni.add(alu);
//                        }
//                    }
//
//                }
                    jt_modulo.setModel(new javax.swing.table.DefaultTableModel(
                            new Object[][]{},
                            new String[]{
                                "ID", "Nombre", "Apellido", "Genero", "Fecha de Nacimiento", "Telefono", "Sueldo", "Años de Experiencia"
                            }
                    ));

                    for (Profesor p : profes) {
                        Object row[] = {p.getId(), p.getNombre(), p.getApellido(), p.getGenero(), p.getFecha_nacimiento(),
                            p.getTelefono(), p.getSueldo(), p.getExperiencia()};
                        DefaultTableModel m = (DefaultTableModel) jt_modulo.getModel();
                        m.addRow(row);
                        jt_modulo.setModel(m);
                    }

                }
            } catch (JedisException e) {
                System.out.println(e);
            }
        } else {
            Redis r = new Redis();
            ArrayList<Alumno> alumnos = new ArrayList();
            try {
                /*for (int i = 0; i < r.getAllKeys().size(); i++) {
                    if (r.readProfesor(r.getAllKeys().get(i)).get("tipo").equals("Alumno")) {
                        Alumno alum = new Alumno(r.readProfesor(r.getAllKeys().get(i)).get("id"),
                                r.readProfesor(r.getAllKeys().get(i)).get("nombre"),
                                r.readProfesor(r.getAllKeys().get(i)).get("apellido"),
                                r.readProfesor(r.getAllKeys().get(i)).get("genero"),
                                r.readProfesor(r.getAllKeys().get(i)).get("fecha_nacimiento"),
                                r.readProfesor(r.getAllKeys().get(i)).get("telefono"),
                                r.readProfesor(r.getAllKeys().get(i)).get("tipo_licencia"));
                        alumnos.add(alum);
                    }
                }*/
            } catch (JedisException e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            if (cb_modulo.getSelectedItem().toString().equals("Profesores")) {
                Profesor pro = profes.get(jt_modulo.getSelectedRow());
                System.out.println(jt_modulo.getSelectedRow());
                tf_editar_profesor_nombre.setText(pro.getNombre());
                tf_editar_profesor_apellido.setText(pro.getApellido());
                if (pro.getGenero().equals("Masculino")) {
                    rb_editar_profesor_male.setSelected(true);
                } else if (pro.getGenero().equals("Femenino")) {
                    rb_editar_profesor_female.setSelected(true);
                }
                Date date = new SimpleDateFormat("yyyy-MM-dd").parse(pro.getFecha_nacimiento());
                jdc_editar_profesor_fecha.setDate(date);
                tf_editar_profesor_telefono.setText(pro.getTelefono());
                sp_editar_profesor_sueldo.setValue(Integer.parseInt(pro.getSueldo()));
                sp_editar_profesor_xp.setValue(Integer.parseInt(pro.getExperiencia()));
                //Abrir dialog
                jd_editar_profesor.setModal(true);//Bloquear otras ventanas
                jd_editar_profesor.pack();//Acoplar el tamaño a la ventana a los elementos que incluye
                jd_editar_profesor.setLocationRelativeTo(this);//Ubicar la ventana en una posicion
                jd_editar_profesor.setResizable(false);//No se puede modificar el tamaño
                jd_editar_profesor.setVisible(true);
            } else {

            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cb_moduloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_moduloItemStateChanged
        if (cb_modulo.getSelectedItem().toString().equals("Profesores")) {
            jt_modulo.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                        "ID", "Nombre", "Apellido", "Genero", "Fecha de Nacimiento", "Telefono", "Sueldo", "Años de Experiencia"
                    }
            ));
            alumni.clear();
        } else {
            jt_modulo.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                        "ID", "Nombre", "Apellido", "Genero", "Fecha de Nacimiento", "Telefono", "Tipo Licencia"
                    }
            ));
            profes.clear();
        }
    }//GEN-LAST:event_cb_moduloItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Redis r = new Redis();
            r.deleteObject(profes.get(jt_modulo.getSelectedRow()).getId());
            profes.remove(jt_modulo.getSelectedRow());
            JOptionPane.showMessageDialog(this, "Eliminó el profesor exitosamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error al eliminar");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        String id = profes.get(jt_modulo.getSelectedRow()).getId();
        //Eliminar
        try {
            Redis r = new Redis();
            r.deleteObject(profes.get(jt_modulo.getSelectedRow()).getId());
            profes.remove(jt_modulo.getSelectedRow());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error al actualizar");
        }
        //Volver a agregar pero con valores nuevos
        try {
            Redis r = new Redis();
            String genero = "";
            if (rb_editar_profesor_male.isSelected()) {
                genero = "Masculino";
            } else {
                genero = "Femenino";
            }
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(jdc_editar_profesor_fecha.getDate());
            Profesor pro = new Profesor(id, tf_editar_profesor_nombre.getText(), tf_editar_profesor_apellido.getText(),
                    genero, date, tf_editar_profesor_telefono.getText(),
                    sp_editar_profesor_sueldo.getValue().toString(), sp_editar_profesor_xp.getValue().toString());
            //Insertar en Redis
            r.createProfesor(pro);
            //Cerrar ventana
            jd_editar_profesor.dispose();
            JOptionPane.showMessageDialog(this, "Se actualizó el profesor exitosamente. \n"
                    + "Su ID es: " + id);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error al actualizar");
        }
    }//GEN-LAST:event_jButton28ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void MI_agregarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_agregarVehiculoActionPerformed
        JD_agregarVehiculo.setModal(true);
        JD_agregarVehiculo.pack();
        JD_agregarVehiculo.setLocationRelativeTo(this);
        JD_agregarVehiculo.setResizable(false);
        JD_agregarVehiculo.setVisible(true);
    }//GEN-LAST:event_MI_agregarVehiculoActionPerformed

    private void MI_agregarClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_agregarClaseActionPerformed
        JD_agregarClase.setModal(true);
        JD_agregarClase.pack();
        JD_agregarClase.setLocationRelativeTo(this);
        JD_agregarClase.setResizable(false);
        JD_agregarClase.setVisible(true);
    }//GEN-LAST:event_MI_agregarClaseActionPerformed

    private void MI_agregarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_agregarPagoActionPerformed
        JD_agregarPago.setModal(true);
        JD_agregarPago.pack();
        JD_agregarPago.setLocationRelativeTo(this);
        JD_agregarPago.setResizable(false);
        JD_agregarPago.setVisible(true);
    }//GEN-LAST:event_MI_agregarPagoActionPerformed

    private void B_agregarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_agregarVehiculoActionPerformed
        try {
            Redis R = new Redis();
            String uniqueID = UUID.randomUUID().toString();
            Vehiculo V = new Vehiculo(uniqueID, TF_uso.getText(),
                    TF_tamano.getText(), TF_tarifa.getText(),
                    TF_consumo.getText(), TF_kmRecorridos.getText(),
                    CB_tipoVehiculo.getItemAt(CB_tipoVehiculo.getSelectedIndex()));
            R.createVehiculo(V);
            JOptionPane.showMessageDialog(JD_agregarVehiculo,
                    "El Vehículo (" + uniqueID + ") se agregó correctamente.");
            JD_agregarVehiculo.dispose();
            TF_uso.setText(null);
            TF_tamano.setText(null);
            TF_tarifa.setText(null);
            TF_consumo.setText(null);
            TF_kmRecorridos.setText(null);
            CB_tipoVehiculo.setSelectedIndex(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(JD_agregarVehiculo, "El Vehículo no se pudo agregar correctamente.");
        }
    }//GEN-LAST:event_B_agregarVehiculoActionPerformed

    private void B_agregarClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_agregarClaseActionPerformed
        try {
            Redis R = new Redis();
            String uniqueID = UUID.randomUUID().toString();
            Clase_Practica C = new Clase_Practica(uniqueID, TF_idProfesor.getText(),
                    TF_idAlumno.getText(), CB_agregarClase_tipoClase.getItemAt(CB_agregarClase_tipoClase.getSelectedIndex()),
                    TF_examenPractico.getText(), TF_examenTeorico.getText());
            R.createClase(C);
            JOptionPane.showMessageDialog(JD_agregarVehiculo,
                    "La Clase (" + uniqueID + ") se agregó correctamente.");
            JD_agregarClase.dispose();
            TF_idProfesor.setText(null);
            TF_idAlumno.setText(null);
            CB_agregarClase_tipoClase.setSelectedIndex(0);
            TF_examenPractico.setText(null);
            TF_examenTeorico.setText(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(JD_agregarClase, "La Clase no se pudo agregar correctamente.");
        }
    }//GEN-LAST:event_B_agregarClaseActionPerformed

    private void B_agregarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_agregarPagoActionPerformed
        try {
            Redis R = new Redis();
            String uniqueID = UUID.randomUUID().toString();
            Pago P = new Pago(uniqueID, TF_agregarPago_idAlumno.getText(),
                    TF_costoMatricula.getText(), TF_costoEnsenanzaTeorica.getText(),
                    TF_costoTramitacionDocs.getText(), TF_costoEnsenanzaPractica.getText());
            R.createPago(P);
            JOptionPane.showMessageDialog(JD_agregarPago,
                    "El Pago (" + uniqueID + ") se agregó correctamente.");
            JD_agregarPago.dispose();
            TF_agregarPago_idAlumno.setText(null);
            TF_costoMatricula.setText(null);
            TF_costoEnsenanzaTeorica.setText(null);
            TF_costoTramitacionDocs.setText(null);
            TF_costoEnsenanzaPractica.setText(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(JD_agregarClase, "El Pago no se pudo agregar correctamente.");
        }
    }//GEN-LAST:event_B_agregarPagoActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_agregarClase;
    private javax.swing.JButton B_agregarPago;
    private javax.swing.JButton B_agregarVehiculo;
    private javax.swing.JComboBox<String> CB_agregarClase_tipoClase;
    private javax.swing.JComboBox<String> CB_tipoVehiculo;
    private javax.swing.JDialog JD_agregarClase;
    private javax.swing.JDialog JD_agregarPago;
    private javax.swing.JDialog JD_agregarVehiculo;
    private javax.swing.JLabel L_agregarClase_tipoClase;
    private javax.swing.JLabel L_agregarPago_idAlumno;
    private javax.swing.JLabel L_clase;
    private javax.swing.JLabel L_consumo;
    private javax.swing.JLabel L_costoEnsenanzaPractica;
    private javax.swing.JLabel L_costoEnsenanzaTeorica;
    private javax.swing.JLabel L_costoMatricula;
    private javax.swing.JLabel L_costoTramitacionDocs;
    private javax.swing.JLabel L_examenPractico;
    private javax.swing.JLabel L_examenTeorico;
    private javax.swing.JLabel L_idAlumno;
    private javax.swing.JLabel L_idProfesor;
    private javax.swing.JLabel L_kmRecorridos;
    private javax.swing.JLabel L_pago;
    private javax.swing.JLabel L_tamano;
    private javax.swing.JLabel L_tarifa;
    private javax.swing.JLabel L_tipoVehiculo;
    private javax.swing.JLabel L_uso;
    private javax.swing.JLabel L_vehiculo;
    private javax.swing.JMenuItem MI_agregarClase;
    private javax.swing.JMenuItem MI_agregarPago;
    private javax.swing.JMenuItem MI_agregarVehiculo;
    private javax.swing.JTextField TF_agregarPago_idAlumno;
    private javax.swing.JTextField TF_consumo;
    private javax.swing.JTextField TF_costoEnsenanzaPractica;
    private javax.swing.JTextField TF_costoEnsenanzaTeorica;
    private javax.swing.JTextField TF_costoMatricula;
    private javax.swing.JTextField TF_costoTramitacionDocs;
    private javax.swing.JTextField TF_examenPractico;
    private javax.swing.JTextField TF_examenTeorico;
    private javax.swing.JTextField TF_idAlumno;
    private javax.swing.JTextField TF_idProfesor;
    private javax.swing.JTextField TF_kmRecorridos;
    private javax.swing.JTextField TF_tamano;
    private javax.swing.JTextField TF_tarifa;
    private javax.swing.JTextField TF_uso;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cb_modulo;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JDialog jd_agregar_alumno;
    private javax.swing.JDialog jd_agregar_profesor;
    private javax.swing.JDialog jd_editar_alumno;
    private javax.swing.JDialog jd_editar_profesor;
    private javax.swing.JDialog jd_login;
    private javax.swing.JDialog jd_modulo;
    private com.toedter.calendar.JDateChooser jdc_editar_profesor_fecha;
    private com.toedter.calendar.JDateChooser jdc_prof_nacimiento;
    private javax.swing.JPanel jp_principal;
    private javax.swing.JTable jt_modulo;
    private javax.swing.JLabel lb_foto;
    private javax.swing.JRadioButton rb_editar_profesor_female;
    private javax.swing.JRadioButton rb_editar_profesor_male;
    private javax.swing.JRadioButton rb_prof_female;
    private javax.swing.JRadioButton rb_prof_male;
    private javax.swing.JSpinner sp_editar_profesor_sueldo;
    private javax.swing.JSpinner sp_editar_profesor_xp;
    private javax.swing.JSpinner sp_prof_sueldo;
    private javax.swing.JSpinner sp_prof_xp;
    private javax.swing.JTextField tf_correo4;
    private javax.swing.JTextField tf_correo5;
    private javax.swing.JTextField tf_correo6;
    private javax.swing.JTextField tf_correo7;
    private javax.swing.JTextField tf_editar_profesor_apellido;
    private javax.swing.JTextField tf_editar_profesor_nombre;
    private javax.swing.JTextField tf_editar_profesor_telefono;
    private javax.swing.JPasswordField tf_login_password;
    private javax.swing.JTextField tf_login_username;
    private javax.swing.JTextField tf_nombre2;
    private javax.swing.JTextField tf_nombre3;
    private javax.swing.JTextField tf_prof_apellido;
    private javax.swing.JTextField tf_prof_nombre;
    private javax.swing.JTextField tf_prof_telefono;
    // End of variables declaration//GEN-END:variables
//int Height = 0, Width = 0;
    ArrayList<Profesor> profes = new ArrayList();
    ArrayList<Alumno> alumni = new ArrayList();
}
